# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageDirectory', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.TextField(max_length=1023)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagText', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='locationAddress',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='locationBio',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='locationType',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint1.Location'),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint1.Location'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint1.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint1.Location'),
        ),
    ]
