# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0005_auto_20170920_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationBio',
            field=models.TextField(max_length=511, null=True),
        ),
    ]
