# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint1', '0006_auto_20171003_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=63, null=True)),
                ('lastName', models.CharField(max_length=63, null=True)),
                ('gender', models.CharField(max_length=31, null=True)),
                ('accountType', models.CharField(max_length=31, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=31, null=True)),
                ('address', models.CharField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
