# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0007_adminviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=254, null=True)),
                ('latitude', models.IntegerField(null=True)),
                ('longtiude', models.IntegerField(null=True)),
                ('locationAddress', models.CharField(max_length=254, null=True)),
                ('locationBio', models.TextField(max_length=511, null=True)),
                ('locationType', models.IntegerField(null=True)),
                ('locationImagePath', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=127)),
                ('imagePath', models.CharField(max_length=127)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminviewer',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminViewer',
        ),
    ]
