# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0011_auto_20171006_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('reportID', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtiude',
            field=models.FloatField(null=True),
        ),
    ]
