# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0011_auto_20171006_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtiude',
            field=models.FloatField(null=True),
        ),
    ]
