# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0013_auto_20171014_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('A', 'Security'), ('B', 'Visual Bug'), ('C', 'Feature Not Working'), ('D', 'Website Crashing'), ('E', 'Other')], max_length=1)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Bugs',
        ),
    ]
