# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0012_auto_20171011_0454'),
        ('sprint1', '0014_auto_20171014_1407'),
    ]

    operations = [
    ]
