# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0012_postimage'),
        ('sprint1', '0016_auto_20171018_0445'),
    ]

    operations = [
    ]
