# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0016_auto_20171018_0445'),
        ('sprint1', '0012_postimage'),
    ]

    operations = [
    ]
