# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint1', '0018_auto_20171031_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailform',
            name='accountType',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='emailform',
            name='firstName',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
